rule.def:
  disable-home-access:
    ref: disable-home-access
    block:
      - /dev/openwrt/access/${dev.mi0}
      - /dev/openwrt/access/${dev.mi1}
      - /dev/openwrt/access/${dev.thinkpad}
      - /dev/openwrt/access/${dev.deimos0}
      - /dev/openwrt/access/${dev.deimos1}

  enable-home-access:
    ref: enable-home-access
    force:
      - /dev/openwrt/access/${dev.mi0}
      - /dev/openwrt/access/${dev.mi1}
      - /dev/openwrt/access/${dev.thinkpad}
      - /dev/openwrt/access/${dev.deimos0}
      - /dev/openwrt/access/${dev.deimos1}

  enable-work-devices:
    ref: enable-work-devices
    force:
      - /dev/openwrt/access/${dev.deimos0}
      - /dev/openwrt/access/${dev.deimos1}

  enable-beamer:
    ref: enable-beamer
    force:
      - /dev/openwrt/access/${dev.proj0}

  disable-beamer:
    ref: disable-beamer
    block:
      - /dev/openwrt/access/${dev.proj0}

  safe-home-browsing:
    ref: safe-home-browsing
    force:
      - /dev/openwrt/dns/208.67.222.123
      - /dev/openwrt/dns/208.67.220.123

  alt-safe-home-browsing:
    ref: alt-safe-home-browsing
    force:
      - /dev/openwrt/dns/208.67.222.222
      - /dev/openwrt/dns/208.67.220.220

  unsafe-home-browsing:
    ref: unsafe-home-browsing
    force:
      - /dev/openwrt/dns/8.8.8.8
      - /dev/openwrt/dns/8.8.4.4

  enable-vpn:
    ref: enable-vpn
    force:
      - /dev/mi/apps/com.celzero.bravedns # prevent uninstall of vpn
      - /dev/mi/vpn/com.celzero.bravedns # always on vpn

  safe-phone-browsing: # TODO maybe use the same as in openwrt?
    ref: safe-phone-browsing
    force:
      - /dev/mi/apps/com.celzero.bravedns/dns/1-bdaacaaaeaaia

  allow-plain-telegram:
    ref: allow-plain-telegram
    # user: id-<(b)ot?>
    # chat: id-<(p)ublic?><(g)iga?><(m)ega?><(c)hannel?><p(o)st?><(s)endMsg?>
    force:
      - /dev/mi/apps/org.telegram.messenger.willpowerless
      - /dev/mi/apps/org.telegram.messenger.willpowerless/users/*-* # any user
    block:
      - /dev/mi/apps/org.telegram.messenger.willpowerless/chats/*-p*-*** # block public & non-mega

  block-food-delivery:
    ref: block-food-delivery
    block:
      - /dev/mi/apps/com.wolt.android
      - /dev/mi/apps/com.ubercab.eats
      - /dev/mi/apps/com.yopeso.lieferando

  block-social:
    ref: block-social
    block:
      - /dev/mi/apps/com.celzero.bravedns/domains/*.tiktokcdn.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.tiktokv.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.youtube.com
#      - /dev/mi/apps/com.celzero.bravedns/domains/*.googlevideo.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.fbcdn.net
      - /dev/mi/apps/com.celzero.bravedns/domains/*.cdninstagram.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.instagram.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.twimg.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.x.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.twitter.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.redd.it
      - /dev/mi/apps/com.celzero.bravedns/domains/*.reddit.com
      - /dev/mi/apps/com.celzero.bravedns/domains/web.telegram.org
      - /dev/mi/apps/com.celzero.bravedns/domains/*.stream.voidboost.cc
      - /dev/mi/apps/com.celzero.bravedns/domains/*.vqserve.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.21wiz.com
      - /dev/mi/apps/com.celzero.bravedns/domains/hdrezka.pro
      - /dev/mi/apps/com.celzero.bravedns/domains/hdrezka.biz
      - /dev/mi/apps/com.celzero.bravedns/domains/rezka.biz
      - /dev/mi/apps/com.celzero.bravedns/domains/*.netflix.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.primevideo.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.amazon.de
      - /dev/mi/apps/com.celzero.bravedns/domains/${custom[0]}
      - /dev/mi/apps/com.celzero.bravedns/domains/${custom[1]}
      - /dev/mi/apps/com.celzero.bravedns/domains/${custom[2]}

      - /dev/mi/apps/com.google.android.youtube
      - /dev/mi/apps/com.netflix.mediaclient
      - /dev/mi/apps/com.falcofemoralis.hdrezkaapp
      - /dev/mi/apps/com.amazon.avod.thirdpartyclient

  block-finance-apps:
    ref: block-finance-apps
    block:
      - /dev/mi/apps/com.starfinanz.smob.android.sfinanzstatus
      - /dev/mi/apps/de.traderepublic.app
      - /dev/mi/apps/com.amazon.mShop.android.shopping

  force-anxiety-journal:
    ref: force-anxiety-journal
    force:
      - /dev/mi/apps/org.telegram.messenger.willpowerless
      - /dev/mi/apps/org.telegram.messenger.willpowerless/users/7125505831-*
    block:
      - /dev/mi/apps/org.telegram.messenger.willpowerless/users/*-*
      - /dev/mi/apps/org.telegram.messenger.willpowerless/chats/*-*

  block-telegram-apps:
    ref: block-telegram-apps
    block:
      - /dev/mi/apps/org.telegram.messenger
      - /dev/mi/apps/*telegram*
      - /dev/mi/apps/app.nicegram
      - /dev/mi/apps/uz.unnarsx.cherrygram
      - /dev/mi/apps/tr.turkgram.messenger
      - /dev/mi/apps/org.vidogram.messenger
      - /dev/mi/apps/org.thunderdog.challegram
      - /dev/mi/apps/com.scriptsaz.litegram
      - /dev/mi/apps/org.vidogram.lite
      - /dev/mi/apps/the.best.gram
      - /dev/mi/apps/tw.nekomimi.nekogram
      - /dev/mi/apps/com.textgram.messenger
      - /dev/mi/apps/com.unigram.app
      - /dev/mi/apps/com.iMe.android
      - /dev/mi/apps/ir.ilmili.telegraph
      - /dev/mi/apps/com.tgconnect.android
      - /dev/mi/apps/com.skyGram.bestt
      - /dev/mi/apps/org.RedGram.messenger
      - /dev/mi/apps/com.xplus.messenger
      - /dev/mi/apps/org.aka.messenger
      - /dev/mi/apps/org.aka.lite
      - /dev/mi/apps/org.plustele.messenger.plus
      - /dev/mi/apps/ellipi.messenger
      - /dev/mi/apps/com.plus.tele.ib
      - /dev/mi/apps/me.teleplus
      - /dev/mi/apps/tg.televpn.messenger
      - /dev/mi/apps/org.telelightpro.messenger
      - /dev/mi/apps/com.w_*
      - /dev/mi/apps/org.metagram.messenger
      - /dev/mi/apps/com.multitoolarlite*
      - /dev/mi/apps/org.thunderdog.challegram
      - /dev/mi/apps/com.storegram.catalog.android
      - /dev/mi/apps/com.gatehousemedia.id3103
      - /dev/mi/apps/org.viento.colibri
      - /dev/mi/apps/com.wTelegrassenger*
      - /dev/mi/apps/com.code0101prime
      - /dev/mi/apps/com.tel.picogramapp

  unblock-phone:
    ref: unblock-phone
    allow:
      - /dev/mi/apps/com.celzero.bravedns/domains/*.tiktokcdn.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.tiktokv.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.youtube.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.googlevideo.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.fbcdn.net
      - /dev/mi/apps/com.celzero.bravedns/domains/*.cdninstagram.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.instagram.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.twimg.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.x.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.twitter.com
#      - /dev/mi/apps/com.celzero.bravedns/domains/*.redd.it
#      - /dev/mi/apps/com.celzero.bravedns/domains/*.reddit.com
      - /dev/mi/apps/com.celzero.bravedns/domains/web.telegram.org
      - /dev/mi/apps/com.celzero.bravedns/domains/*.stream.voidboost.cc
      - /dev/mi/apps/com.celzero.bravedns/domains/*.vqserve.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.21wiz.com
      - /dev/mi/apps/com.celzero.bravedns/domains/hdrezka.pro
      - /dev/mi/apps/com.celzero.bravedns/domains/hdrezka.biz
      - /dev/mi/apps/com.celzero.bravedns/domains/rezka.biz
      - /dev/mi/apps/com.celzero.bravedns/domains/*.netflix.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.primevideo.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.amazon.de

      - /dev/mi/apps/com.google.android.youtube
      - /dev/mi/apps/com.netflix.mediaclient
      - /dev/mi/apps/com.falcofemoralis.hdrezkaapp
      - /dev/mi/apps/com.amazon.avod.thirdpartyclient

      - /dev/mi/apps/com.wolt.android
      - /dev/mi/apps/com.ubercab.eats
      - /dev/mi/apps/com.yopeso.lieferando

      - /dev/mi/apps/com.starfinanz.smob.android.sfinanzstatus
      - /dev/mi/apps/de.traderepublic.app
      - /dev/mi/apps/com.amazon.mShop.android.shopping

      - /dev/mi/apps/org.telegram.messenger.willpowerless/users/*-*
      - /dev/mi/apps/org.telegram.messenger.willpowerless/chats/*-*

  disable-mobile-data:
    ref: disable-mobile-data
    block:
      - /dev/mi/access/sim.de # name or mac?? // TODO

  block-gaming-domains:
    ref: block-gaming-domains
    block:
      - /dev/deimos/domain/steam  # TODO

  block-phone-everything:
    ref: block-phone-everything
    block:
      - /dev/mi/apps/* # TODO
