law.def:
  - name: "✅ Allow Restoration"
    description: Allow everything in order to rest and recover in case of sickness or vacation
    verify:
      - type: CalenderAbsenceVerifier
        expiryToDurationRate: 1.8  # 1.8 (e.g. 10 days absence -> +10/1.8 ~ +5.5 days expiry)
        maxExpiry: 7d
        minExpiry: 0d
    out:
      - ${rule.def.enable-home-access.ref}
      - ${rule.def.enable-beamer.ref}

  # Service times, when is needed anyway
  - name: "✅ Allow Beamer during day for others"
    description: Allow beamer, since others are involved
    enabled: false
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY ]
        timeRange: 11:00 - 15:00
    out:
      - ${rule.def.enable-beamer.ref}

  - name: "✅ Allow home office"
    description: Allow internet access during home office hours
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY ]
        timeRange: 11:00 - 15:00
    out:
      - ${rule.def.enable-work-devices.ref}

  # General use and moderations of internet
  - name: "✅ Allow Night Beamer"
    description: Allow night beamer, since others are involved
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 21:30 - 23:59
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 00:00 - 01:30 # first rethink barrier (30 min)
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 02:00 - 03:00 # second rethink barrier (15 min)
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 03:15 - 11:00
    out:
      - ${rule.def.enable-beamer.ref}

  - name: "✅ Allow Night Access"
    description: Allow night access, since its unlikely to get abused
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 00:00 - 11:00
    out:
      - ${rule.def.enable-home-access.ref}

  - name: "⛔ Force Gym"
    description: Force regular gym visits, disabling normal access
    enabled: false
    verify:
      - type: WellpassVerifier
        regex: .*(leipzig|plagwitz).*
        expiry: 4d
        cache: 2h
    out:
      - ${rule.def.disable-home-access.ref}
      - ${rule.def.disable-beamer.ref}

  - name: "✅ Regular Use"
    description: Enable regular use of internet
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ WEDNESDAY, THURSDAY, FRIDAY ]
        timeRange: 00:00 - 23:59
    out:
      - ${rule.def.enable-home-access.ref}
      - ${rule.def.enable-beamer.ref}

  - name: "⛔ Touch grass"
    description: Disable access by default
    out:
      - ${rule.def.disable-home-access.ref}
      - ${rule.def.disable-beamer.ref}

  # Mobile device moderations
  - name: "⛔ Force anxiety journaling"
    description: Force everyday journaling of anxiety
    operator: all
    verify:
      - type: AnxietyJournalVerifier
        minWords: 30
        cosineThreshold: 0.75
        jaccardThreshold: 0.85
        cosineJaccardSumThreshold: 1.6
        expiry: 5d
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY ]
        timeRange: 14:00 - 20:00
    out:
      - ${rule.def.force-anxiety-journal.ref}

  - name: "🟡 Moderate food delivery"
    description: Prohibit too much ordering food at home
    out:
      - ${rule.def.block-food-delivery.ref}

  - name: "🟡 Moderate Money Spending"
    description: Prohibit too much spending and card money movement outside of budget
    out:
      - ${rule.def.block-finance-apps.ref}

  - name: "🟡 Moderate A"
    description: Prohibit overconsumption of A
    out:
      - ${rule.def.safe-home-browsing.ref}
      - ${rule.def.enable-vpn.ref}
      - ${rule.def.safe-phone-browsing.ref}

  - name: "🟡 Moderate Social"
    description: Prohibit overconsumption of social media and brain rotting
    out:
      - ${rule.def.enable-vpn.ref}
      - ${rule.def.block-social.ref}

      - ${rule.def.allow-plain-telegram.ref}
      - ${rule.def.block-telegram-apps.ref}